---
- name : deploying package
  hosts : PROD
  become : yes
  vars : 
    USERNAME : tom_user
    TOMCAT_PATH : /tomcat
    TOMCAT_URL : https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
    WAR_PATH : /tomcat/apache-tomcat-9.0.65/webapps
    WAR_URL : http://3.110.179.142:8081/repository/maven-snapshots/com/ksapp/ks/6-SNAPSHOT/ks-6-20220824.113938-2.war
    WAR_PACK : tomcat/apache-tomcat-9.0.65/webapps/ks.war
  tasks :
    - name : creating tomcat user
      ansible.builtin.user:
        name : "{{USERNAME}}"

    - name : create a directory for tomcat
      file : 
        path : "{{TOMCAT_PATH}}"
        state : directory
        owner : "{{USERNAME}}"
        group : "{{USERNAME}}"
        mode : 0775
        recurse : yes

    - name : download tomcat
      ansible.builtin.unarchive:
        src: "{{TOMCAT_URL}}"
        dest: "{{TOMCAT_PATH}}"
        remote_src: yes
      become_user : "{{USERNAME}}"
    
    - name: remove files and directories
      file:
        state: "{{item}}"
        path: "{{WAR_PATH}}"
        owner: "{{USERNAME}}"
        group: "{{USERNAME}}"
      with_items:
        - absent
        - directory

    - name : deploying war package
      get_url :
        url : "{{WAR_URL}}"
        dest : "{{WAR_PACK}}"
      became_user :      