---
- name : deploying package
  hosts : PROD
  become : yes
  vars : 
    USERNAME : tom_user
    TOMCAT_PATH : /tomcat
    TOMCAT_URL : 
  tasks :
    - name : creating tomcat user
      ansible.builtin.user:
        name : "{{USERNAME}}"

    - name : create a directory for tomcat
      file : 
        path : "{{TOMCAT_PATH}}"
        state : directory
        owner : "{{USERNAME}}"
        group : "{{USERNAME}}"
        mode : 0775
        recurse : yes
         