---
- name : deploying package
  hosts : PROD
  become : yes
  vars : 
    USERNAME : tom_user
    TOMCAT_PATH : /tomcat
    TOMCAT_URL : https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
  tasks :
    - name : creating tomcat user
      ansible.builtin.user:
        name : "{{USERNAME}}"

    - name : create a directory for tomcat
      file : 
        path : "{{TOMCAT_PATH}}"
        state : directory
        owner : "{{USERNAME}}"
        group : "{{USERNAME}}"
        mode : 0775
        recurse : yes

      - name : download tomcat
        ansible.builtin.unarchive:
          src: "{{TOMCAT_URL}}"
          dest: "{{TOMCAT_PATH}}"
          remote_src: yes
        become_user : "{{USERNAME}}"
